#!/usr/bin/env python3
"""Generate the Windows VERSIONINFO resource for the packaged executable.

The asset filename stays EQLCompanion.exe on purpose — GitHub's
`/releases/latest/download/<name>` permalink only resolves for a stable
name, desktop shortcuts survive an in-place replacement, and the data folder
sits beside the exe, so accumulating copies would scatter it. The version
belongs INSIDE the file instead, where Windows already looks: right-click →
Properties → Details, Explorer's "File version" column, and whatever the
user's antivirus or IT tooling reads.

Run from the repo root; writes build/version_info.txt for --version-file.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "build" / "version_info.txt"

TEMPLATE = """# Generated by scripts/make_version_file.py — do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({a}, {b}, {c}, 0),
    prodvers=({a}, {b}, {c}, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', 'EQL Companion contributors'),
         StringStruct('FileDescription',
                      'EQL Companion — live companion for EverQuest Legends'),
         StringStruct('FileVersion', '{ver}'),
         StringStruct('InternalName', 'EQLCompanion'),
         StringStruct('LegalCopyright',
                      'MIT licensed. Reads your log; never touches the game.'),
         StringStruct('OriginalFilename', 'EQLCompanion.exe'),
         StringStruct('ProductName', 'EQL Companion'),
         StringStruct('ProductVersion', '{ver}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def app_version() -> str:
    """Single source of truth: APP_VERSION in backend/main.py."""
    text = (ROOT / "backend" / "main.py").read_text(encoding="utf-8")
    m = re.search(r'APP_VERSION\s*=\s*"([0-9]+)\.([0-9]+)\.([0-9]+)"', text)
    if not m:
        raise SystemExit("APP_VERSION not found in backend/main.py")
    return m.group(0).split('"')[1]


def main() -> None:
    ver = app_version()
    a, b, c = ver.split(".")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(TEMPLATE.format(a=a, b=b, c=c, ver=ver), encoding="utf-8")
    print(f"version resource for {ver} -> {OUT}")


if __name__ == "__main__":
    sys.exit(main())
